(define (problem DELIVERY-1)
(:domain DELIVERY)
(:objects A B C Z P)
(:INIT  (empty)
        (can-move Z)
        (connected A B)
        (connected B A)
        (connected B C)
        (connected C B)
        (in Z A)
        (in P C))
(:goal (in P B))
)