(define (problem ROBOT-1)
(:domain DELIVERY)
(:objects A B R P)
(:INIT  (connected A B)
        (connected B A)
        (can-move R)
        (empty)
        (in R A)
        (in P B))
(:goal (in P A))
)