(define (problem DELIVERY-1)
(:domain DELIVERY)
(:objects A B C D E F G H Z P)
(:INIT  (empty)
        (can-move Z)
        (connected A B)
        (connected B A)
        (connected B C)
        (connected C B)
        (connected B D)
        (connected D B)
        (connected D E)
        (connected E D)
        (connected E F)
        (connected F E)
        (connected F G)
        (connected G F)
        (connected F H)
        (connected H F)
        (in Z A)
        (in P C))
(:goal (in P G))
)