(define (problem TAXI-1)
	(:domain TAXI)
	(:objects TAXI P1 P2 P3 A B C D E F G H I J K L)
	(:INIT (connected A B)
		   (connected B C)
		   (connected C D)
		   (connected D H)
		   (connected C G)
		   (connected B F)
		   (connected A E)
		   (connected E F)
		   (connected F G)
		   (connected G H)
		   (connected E I)
		   (connected F J)
		   (connected G K)
		   (connected H L)
		   (connected I J)
		   (connected J K)
		   (connected K L)
		   (is-cab TAXI)
		   (multi-ride P1)
		   (multi-ride P2)
		   (multi-ride P3)
		   (on P1 A)
		   (on P2 L)
		   (on P3 I)
		   (on TAXI H))
	(:goal (and (on P1 D)
		   (on P2 F)
		   (on P3 G)))
)