(define (problem TAXI-1)
	(:domain TAXI)
	(:objects TAXI P1 P2 P3 A B C D E F G H I J K L M N O P Q R S T)
	(:INIT (connected A B)
	       (connected B C)
	       (connected C E)
	       (connected E F)
	       (connected F G)
	       (connected F I)
	       (connected G H)
	       (connected H I)
	       (connected i j)
	       (connected j k)
	       (connected k l)
	       (connected l e)
	       (connected m e)
	       (connected m n)
	       (connected n o)
	       (connected o p)
	       (connected p n)
	       (connected p d)
	       (connected p g)
	       (connected g r)
	       (connected r m)
	       (connected r s)
	       (connected s t)
		   (is-cab TAXI)
		   (multi-ride P1)
		   (multi-ride P2)
		   (multi-ride P3)
		   (on P1 g)
		   (on P2 L)
		   (on P3 f)
		   (on P4 e)
		   (on P5 A)
		   (on TAXI t))
	(:goal (and (on P1 o)
		   (on P2 o)
		   (on P3 o)
		   (on P4 t)
		   (on P5 t)))
)